### ISSUE TITLE
Generated documentation is broken for URLs with hyphens

### ISSUE THREAD

**Issue by wolfgang42** [mulesoft-labs/raml-javascript-generator#4]
I have a URL /parse-order in my API. For this URL the following documentation is generated:
>#### resources.parse-order
>
>```js
>var resource = client.resources.parse-order;
>```

However the actual code that is generated uses camelCase, so the documentation should instead read:
```js
var resource = client.resources.parseOrder;
```

**Comment by blakeembrey** [comment]
@wolfgang42 Thanks for the report! I've fixed the issue and released a patch version which camel cases the keys in the README.
